import numpy as np
import pandas as pd
import networkx as nx
from Xnode2vec import complete_edgelist, stellar_edgelist, generate_edgelist, edgelist_from_csv
import pytest

def test_complete_dimension():
    """
    Description
    -----------
    Test of complete_edgelist() function.
    Checks if the length of the edgelist generated by complete_edgelist() is equal to the number of points of the
    dataset squared.
    """
    rows = np.random.randint(1,30)
    columns = np.random.randint(1,30)
    dataset = np.random.rand(rows,columns)
    assert len(complete_edgelist(dataset).index) == dataset.shape[0]**2

def test_stellar_dimension():
    """
    Description
    -----------
    Test of stellar_edgelist() function.
    Checks if the length of the edgelist generated by stellar_edgelist() is equal to the number of points of the
    dataset.
    """
    rows = np.random.randint(1,30)
    columns = np.random.randint(1,30)
    dataset = np.random.rand(rows,columns)
    assert len(stellar_edgelist(dataset).index) == dataset.shape[0]

def test_complete_zeroweight():
    """
    Description
    -----------
    Test of complete_edgelist() function.
    Checks if the weights of a dataset with zero distance between all the points is 1, except for the self links that
    must be 0.
    """
    rows = np.random.randint(1, 30)
    columns = np.random.randint(1, 30)
    dataset = np.ones((rows, columns))
    df = complete_edgelist(dataset)
    unique, counts = np.unique(df['weight'].values, return_counts = True)
    assert counts[0] == rows # Number of self links
    assert counts[1] == rows**2 - rows # The rest of the links

def test_stellar_zeroweight():
    """
    Description
    -----------
    Test of stellar_edgelist() function.
    Checks the data types of the produced list for the stellar_edgelist function.
    """
    rows = np.random.randint(1, 30)
    columns = np.random.randint(1, 30)
    dataset = np.zeros((rows, columns))
    assert stellar_edgelist(dataset).loc[:,'weight'].values.all() == 1.

def test_complete_checktypes():
    """
    Description
    -----------
    Test of complete_edgelist() function.
    Checks the data types of the produced list for the complete_edgelist() function.
    """
    rows = np.random.randint(1, 30)
    columns = np.random.randint(1, 30)
    dataset = np.zeros((rows, columns))
    df = complete_edgelist(dataset)
    assert (all(isinstance(item, str) for item in df['node1'].values),
            all(isinstance(item, str) for item in df['node2'].values),
            all(isinstance(item, float) for item in df['weight'].values)) == (True,True,True)

def test_complete_stretch():
    """
    Description
    -----------
    Test of complete_edgelist() function.
    Checks if the assigned weights are all 0 if 'stretch' parameter is 0.0001 -- zero. The expected vector has dimension
     'row**2', since it represents a completely connected network.
    """
    rows = np.random.randint(1, 30)
    columns = np.random.randint(1, 10)
    dataset = np.random.rand(rows, columns)
    df = complete_edgelist(dataset, stretch = 0.0001)
    assert np.array_equal(np.round(df['weight'].values, decimals = 20), np.zeros(rows**2))
    
def test_stellar_checktypes():
    """
    Description
    -----------
    Test of stellar_edgelist() function.
    Checks the data types of the produced list for the stellar_edgelist() function.
    """
    rows = np.random.randint(1, 30)
    columns = np.random.randint(1, 30)
    dataset = np.zeros((rows, columns))
    df = stellar_edgelist(dataset)
    assert (all(isinstance(item, str) for item in df['node1'].values),
            all(isinstance(item, str) for item in df['node2'].values),
            all(isinstance(item, float) for item in df['weight'].values)) == (True, True, True)

def test_nxedgelist_samenode():
    """
    Description
    -----------
    Test of generate_edgelist() function.
    Checks if inserting the same point will produce a network of dimension 1.
    """
    rows = np.random.randint(1, 30)
    narray = np.ones((rows, 3))
    df = pd.DataFrame(narray, columns = ['node1', 'node2', 'weight'])
    df = generate_edgelist(df)
    G = nx.Graph()
    G.add_weighted_edges_from(df)
    assert len(list(G.nodes)) == 1

def test_from_csv():
    """
    Description
    -----------
    Test of edgelist_from_csv() function.
    Checks if the inserted .csv file produces the expected edgelist.
    """
    edgelist = edgelist_from_csv('generic_edgelist.csv')
    assert edgelist == [('1','2',0.7),('1','4',5),('2','3',3),('2','4',1.7)]
